SUPPORTED_MATRIX = [
  ("windows", "amd64"),
  ("windows", "x86"),
  ("macos", "amd64"),
  ("linux", "amd64"),
  ("linux", "x86"),
  ("linux", "arm64"),
  ("linux", "arm"),
  ("linux", "mips64"),
  ("linux", "mips"),
  ("linux", "mips64le"),
  ("linux", "mipsle"),
  ("linux", "s390x"),
  ("freebsd", "amd64"),
  ("freebsd", "x86"),
  ("openbsd", "amd64"),
  ("openbsd", "x86"),
  ("dragonfly", "amd64"),
]
